#setwd("/Users/diva/Downloads/4th semestr /Exploratory Data Analysis/oscar")
#by Diva

#Exploratory Data Analysis

#1.Loading the necessary packages
install.packages("visdat")
library(visdat)
library(tidyverse)
library(dplyr)
library(readr)
library(ggplot2)


#2.Importing our datasets
movies <- read_csv("data/movies.csv")
oscars <- read_csv("data/oscars.csv")

#3.Exploring the structure of the dataset
str(movies)
head(movies)
summary(movies)
#Description
#The dataset contains information about movies from the years 1980 to 2020, 
#including various attributes such as name, rating, genre, year, release date, score, votes, director, writer, star, country, budget, gross, company, and runtime. 
#Each row in the dataset represents a different movie, and each column represents a specific attribute of the movie.

#Here is a breakdown of the columns in the dataset:

# - Name: The title or name of the movie.
# - Rating: The rating assigned to the movie (e.g., R, PG, etc.), indicating the intended audience age group.
# - Genre: The genre or category of the movie (e.g., Drama, Adventure, Comedy, etc.).
# - Year: The year when the movie was released.
# - Released: The specific release date of the movie, including the country of release.
# - Score: The average rating or score given to the movie.
# - Votes: The number of votes or ratings received by the movie.
# - Director: The name of the director of the movie.
# - Writer: The name of the writer or screenplay writer of the movie.
# - Star: The name of the lead actor or actress in the movie.
# - Country: The country of origin or production of the movie.
# - Budget: The budget or estimated cost of producing the movie.
# - Gross: The total gross revenue or earnings generated by the movie.
# - Company: The production company associated with the movie.
# - Runtime: The duration or runtime of the movie in minutes.



str(oscars) #type of Year is character 
head(oscars)
summary(oscars)
oscars$Year <- as.numeric(oscars$Year) # we don't care about NAs introduced by coercion in the beginning of dataset, as in "movies" dataset data starts from year 1980. 
#Description 
#The dataset consists of information about award winners at various film ceremonies from the years 1927 to 2015. 
#Each entry in the dataset represents a specific award category and includes details 
#such as the year of the ceremony, the ceremony number, the award category, the winner's name, and the film associated with the award.


# Here is a breakdown of the columns in the dataset:
#   
# - Year: The year of the film ceremony.
# - Ceremony: The ceremony number or identifier.
# - Award: The category of the award.
# - Winner: Indicates whether the winner is the first winner mentioned for the award category. The value "1" signifies the first winner.
# - Name: The name of the winner.
# - Film: The film associated with the award.

##Our goal is to provide insights into what movies to succeed at the Oscars,so we can partly omit data from datasets, so there will be data on Oscars ceremonies and films from the years 1980 to 2015.
filtered_movies <- movies[movies$year >= 1980 & movies$year <= 2015, ]
filtered_oscars <- oscars[oscars$Year >= 1980 & oscars$Year <= 2015, ]
summary(filtered_movies)
summary(filtered_oscars)


#4.Handling missing values and data cleaning
missing_movies <- is.na(filtered_movies)
missing_movies
summary_movies <- colSums(missing_movies)
summary_movies # there are 1912 missing values in budget, that is quite a lot, we won't omit it for now.

missing_oscars <- is.na(filtered_oscars) 
missing_oscars
summary_oscars <- colSums(missing_oscars)
summary_oscars 

#Visualizing missing values 
vis_miss(filtered_movies)
vis_miss(filtered_oscars)

#Deleting all the rows with missing rating and/or gross from movies dataset 
movies_no_missing <- filtered_movies[complete.cases(filtered_movies[c("name", "rating", "genre", "year", "released", "score", "votes", "director", "writer", "star", "country", "gross", "company", "runtime")]), ]
#double checking 
vis_miss(movies_no_missing)
#for later analysis preparing dataset with cleaned budget.
movies_no_missing_budget <- na.omit(movies_no_missing[c("budget")])

#Setting values 0 insted of NA for false winners in oscars dataset.
filtered_oscars$Winner[is.na(filtered_oscars$Winner)] <- 0
#Omiting missing values from oscars dataset
oscars_no_missing <- na.omit(filtered_oscars)
oscars_no_missing
#double checking 
vis_miss(oscars_no_missing)


view(oscars_no_missing)
#Almost all instances have switched Film and Name, except Actors and Actresses.
#Fixing the data

##Creating a vector of the four award categories where the Name and Film columns are already correct.
correct_awards <- c("Actor in a Leading Role", "Actor in a Supporting Role", 
                    "Actress in a Leading Role", "Actress in a Supporting Role")

##Creating a new df that contains only the rows where the Award column is not in the correct_awards vector.
data_fix = oscars_no_missing[!(oscars_no_missing$Award %in% correct_awards), ]
##Creating a variable to store the values of the Film column for the rows in data_fix
cat_name = data_fix$Film
##Creating a variable to store the values of the Name column for the rows in data_fix
cat_film = data_fix$Name
##Swapping the values of the Name and Film columns for the rows that are not in the correct_awards vector
oscars_no_missing[!(oscars_no_missing$Award %in% correct_awards), 5] = cat_name
oscars_no_missing[!(oscars_no_missing$Award %in% correct_awards), 6] = cat_film

view(oscars_no_missing)


# Joining two datasets based on the name of the film.
df <- inner_join(oscars_no_missing, movies_no_missing, by = c("Film" = "name"))
# Convert year released column to Date format
df$year_released <- as.Date(df$year_released, "%B %d, %Y (%A)")
view(df)

#write.csv(df, "cleaned_merged.csv", row.names = FALSE)



#5.Summarizing and visualizing the data
summary(df)
#Creating a scatter plot of votes vs. gross
plot(df$votes, df$gross)

# Create a correlation matrix
cor(df[, c("score", "votes", "budget", "gross")])
# High correlation between score and votes, gross and votes 

# Create a scatterplot of budget vs gross
ggplot(df, aes(x=budget, y=gross)) + 
  geom_point() + 
  labs(title="Budget vs Gross", x="Budget", y="Gross")

# Create a boxplot of scores by genre
ggplot(df, aes(x=genre, y=score)) + 
  geom_boxplot() + 
  labs(title="Scores by Genre", x="Genre", y="Score")

#6.Analyzing relationships and patterns:


##Winner = high score?
#We assume, that Oscar-winning films tend to have higher ratings. Let's test this hypothesis using t-test. 
#Creating a variable indicating whether or not the film won an Oscar
df$Won_Oscar <- ifelse(df$Winner == 1, "Yes", "No")

#Computing the mean score for films that won an Oscar
mean_score_oscar <- mean(df[df$Won_Oscar == "Yes",]$score)
#Computing the mean score for films that did not win an Oscar
mean_score_no_oscar <- mean(df[df$Won_Oscar == "No",]$score)

#Performing a t-test to compare the two means
t.test(df[df$Won_Oscar == "Yes",]$score, df[df$Won_Oscar == "No",]$score)

#The p-value is less than 2.2e-16, which means that there is strong evidence to reject the null hypothesis that the mean scores of films that won an Oscar is equal to the mean scores of films that did not win an Oscar. 
#The sample mean of scores for Oscar-winning films is 7.68, and for non-Oscar-winning films, it is 7.39. This suggests that, on average, Oscar-winning films tend to have higher scores than non-Oscar-winning films.




##Another assumption is that certain genres may be more likely to win awards.
#Visualize the genres that won the Oscar price.
# create a new data frame with only the necessary columns
df_genres <- df %>% select(genre, Winner)
# filter for only the winners
df_genres <- df_genres %>% filter(Winner == 1)
# group by genre and count the number of awards won for each
df_genres_count <- df_genres %>% group_by(genre) %>% summarize(wins = n())
# create the bar plot
ggplot(df_genres_count, aes(x = genre, y = wins)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Genre") +
  ylab("Number of Awards Won") +
  ggtitle("Genres That Won at Oscars")

#As we can see, Drama and Biography are more likely to win awards.

#To determine if certain genres are more likely to win awards, we can perform a statistical test. Here, we can use a chi-squared test to see if there is a significant association between the genre of a film and whether it won an award or not. 
  
#Creating a contingency table of genres vs. awards
genre_award_table <- table(df$genre, df$Winner)

#Performing the chi-squared test
chi_sq_result <- chisq.test(genre_award_table)

print(chi_sq_result)
#The p-value = 0.07037, it means that there is not enough evidence to reject the null hypothesis that there is no association between a genre of a film and whether it won an award or not. 
#Therefore, we cannot conclude that there is a significant association between the two variables based on the results of the test.



#Some categories may be more competitive than others, and some may have more predictable winners based on historical trends.

#creating a new df with only the necessary columns
df_awards <- df %>% select(Award, Winner)
#filtering for only the winners
df_awards <- df_awards %>% filter(Winner == 1)
#grouping by genre and counting the number of awards won for each
df_awards_count <- df_awards %>% group_by(Award) %>% summarize(wins = n())

#sorting by wins in descending order and selecting the top 10
top_10_awards <- df_awards_count %>% 
  arrange(desc(wins)) %>% 
  slice(1:10)
# the bar plot
ggplot(top_10_awards, aes(x = Award, y = wins)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  xlab("Award") +
  ylab("Number of Awards Won") +
  ggtitle("Awards That Won at Oscars")

#Awards that mostly won at Oscars: Actor in a Leading Role , Best Picture, Film Editing, Actress in a Supporting Role, Costume Design, Directing.

#To analyze whether some categories are more competitive than others, we can use logistic regression.
#Creating new is_winner column
df$is_winner <- as.numeric(df$Winner == 1)
#Fitting logistic regression model
model_1 <- glm(is_winner ~ Award + genre, data = df, family = binomial())

summary(model)

#Making predictions on test data
test_data <- data.frame(Award = "Actor in a Leading Role", genre = "Drama")
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Actor in a Leading Role", genre = "Biography")
predict(model, newdata = test_data, type = "response")

test_data <- data.frame(Award = "Best Picture", genre = "Drama")
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Best Picture", genre = "Biography")
predict(model, newdata = test_data, type = "response")

test_data <- data.frame(Award = "Film Editing", genre = "Drama") #the highest probability of winning for a combination of award category and genre "Drama", which equals 0.225205.
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Film Editing", genre = "Biography")
predict(model, newdata = test_data, type = "response") #the highest probability of winning for a combination of award category and genre "Biography", which equals 0.2756025.

test_data <- data.frame(Award = "Actress in a Supporting Role", genre = "Drama")
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Actress in a Supporting Role", genre = "Biography")
predict(model, newdata = test_data, type = "response")

test_data <- data.frame(Award = "Costume Design", genre = "Drama")
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Costume Design", genre = "Biography")
predict(model, newdata = test_data, type = "response")

test_data <- data.frame(Award = "Directing", genre = "Drama")
predict(model, newdata = test_data, type = "response")
test_data <- data.frame(Award = "Directing", genre = "Biography")
predict(model, newdata = test_data, type = "response")

#The model predicts a probability of 0.225205 of winning the award in the "Film Editing" category, while for the "Biography" genre, the model predicts a higher probability of 0.2756025. 
#If your movie falls under the Biography genre, the chances of winning an award are higher compared to other genres.
#However if your movie falls under the Drama genre, the chances of winning an award in the "Film Editing" category are higher compared to other categories.

##Director, writer, and star: These individuals may have a significant impact on the score and success of a film.
#Building models
model_2 <- lm(score ~ director + writer + star, data = df)
model_3 <- lm(is_winner ~ director + writer + star, data = df)

#Summarizing
summary(model_2) # p-values for the director, writer, and star are  significant,  we can conclude that these variables have a significant impact on a film's score.
#Negative values suggest that the director is associated with lower values of the response variable, whereas positive values suggest that the director is associated with higher values of the response variable.

summary(model_3) #none of the director, writer, or star variables have statistically significant effects on the likelihood of winning an award, as their p-values are all greater than 0.05.
#However, there may be other important variables not included in the model.


##Another assumption we want to check is whether films from certain countries may have an advantage over others or not.
#Visualization of winners by countries:
#creating a new data frame with only the necessary columns
df_countries <- df %>% select(country, Winner)
#filtering for only the winners
df_countries <- df_countries %>% filter(Winner == 1)
#grouping by country and count the number of awards won for each
df_countries_count <- df_countries %>% group_by(country) %>% summarize(wins = n())

top_5_countries <- df_countries_count %>% 
  arrange(desc(wins)) %>% 
  slice(1:5)
#plot bar chart of wins counts by country
ggplot(top_5_countries, aes(x = country, y = wins)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Country") +
  ylab("Number of Awards") +
  ggtitle("Number of Awards Won by Country")

#The United States has the highest number of Oscar winners.

#Visualization of total gross earnings by countries:
df_countries_gross <- df %>% select(country, gross)
#grouping by genre and count the number of awards won for each
df_countries_gross <- df_countries_gross %>% group_by(country) %>% summarize(total_gross = sum(gross))

top_5_countries_gross <- df_countries_gross %>% 
  arrange(desc(total_gross)) %>% 
  slice(1:5)
#a box plot of gross by country
ggplot(top_5_countries_gross, aes(x = country, y = total_gross)) +
  geom_bar(stat = "identity", fill = "orange") +
  xlab("Country") +
  ylab("Total Gross earnings") +
  ggtitle("Total Gross earnings by Country")
#The United States still has the highest amount of total gross earnings. UK has almost the same amount of gross earnings with New Zealand, but significantlly higher number of wins.


#We can perform a hypothesis test to see if there is a significant difference in the average gross revenue between films from different countries. 
#We can use ANOVA test for this purpose. 
#H0: there is no difference in the average gross revenue between films from different countries.
#H1: there is a difference.
result <- aov(gross ~ country, data = df)
summary(result)
#F-value for the country variable is 8.386, which is statistically significant with a p-value of < 0.001. 
#This suggests that there is a significant difference in gross earnings between the countries.
#However,there is some unexplained variability in gross earnings that can be affected by other variables.



#Checking if higher grossing films are more popular.
movies_sub <- subset(df, select = c("budget", "gross", "score", "votes"))

#Scatterplot of budget vs. gross
plot(movies_sub$budget, movies_sub$gross, xlab = "Budget", ylab = "Gross", main = "Budget vs. Gross")

#Correlation between budget and gross
movies_sub <- na.omit(movies_sub)
cor(movies_sub$budget, movies_sub$gross) #0.7266202
#Higher budget films tend to gross more.

#Scatterplot of score vs. votes
plot(movies_sub$score, movies_sub$votes, xlab = "Score", ylab = "Votes", main = "Score vs. Votes")

#Correlation between score and votes
cor(movies_sub$score, movies_sub$votes) #0.6841681
#Higher grossing films tend to have higher scores!



##Testing if longer films may be viewed as more deserving awards films.
#Plotting the relationship between film runtime and awards won: 
#filtering data for films from year 1980
#scratter plot of awards won against runtime
ggplot(df, aes(x=runtime, y=score)) + 
  geom_point() +
  xlab("Runtime (minutes)") +
  ylab("Score") +
  ggtitle("Relationship between film runtime and score")

cor(df$runtime,df$score) #weak correlation

#I found that certain genres, such as drama and biography, are more likely to receive Oscar nominations and wins. 
#Additionally, movies with higher budgets and box office earnings are also more likely to receive nominations and wins. We also found that certain Oscar categories, such as Best Picture and Best Director, are more influenced by movie characteristics such as genre, budget, and box office earnings.
#The most succesfull combination for winning Oscar is if ur film in genre "Biorgraphy" and nominating for "Film Editing" award. 
#These findings can be valuable for filmmakers and studios aiming to increase their chances of receiving an Oscar nomination or win. Overall, the analysis provided a better understanding of the factors that make a movie successful at the Oscars.





